-- TODO: https://www.reddit.com/r/neovim/comments/15z0y2j/need_help_i_am_having_trouble_getting/

require('user.colors')
require('user.hop')
require('user.vimprefs')
require('user.telescope')
require('user.outline')
require('user.filetree')
require('user.indentation')
require('user.surround')
require('user.lualine')
require('user.treesitter')
require('user.keymaps')
require('user.lsp')
require('user.quickfix')
